name: Docker Compose CI

on: 
  push:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Validacion de docker compose
      - name: Validate docker-compose
        run: docker compose config

      - name: Build and start containers
        run: docker compose up --build -d

      # El backend responde en /api/Event? 
      - name: Test backend API
        run: |
          for i in {1..10}; do
            if curl -sSf http://localhost:8000/api/Event > /dev/null; then
              echo "Backend is up and responding"
              exit 0
            fi
            echo "Backend not ready yet... retrying ($i/10)"
            sleep 5
          done
          echo "Backend did not respond in time"
          exit 1

      # Probar que el frontend responde en puerto 80
      - name: Test frontend
        run: |
          for i in {1..10}; do
            if curl -sSf http://localhost:80 > /dev/null; then
              echo "Frontend is up and responding"
              exit 0
            fi
            echo "Frontend not ready yet... retrying ($i/10)"
            sleep 5
          done
          echo "Frontend did not respond in time"
          exit 1
      
      # Verificar que la API devuelve JS correcto
      - name: Validate backend JSON response
        run: |
          response=$(curl -s http://localhost:8000/api/Event)

          # Validar que existe "pagination" y "events"
          echo "$response" | jq -e '.pagination.count' > /dev/null || (echo "No pagination.count field" && exit 1)
          echo "$response" | jq -e '.events[0].id' > /dev/null || (echo "No events[0].id field" && exit 1)
          echo "$response" | jq -e '.events[0].titulo' > /dev/null || (echo "No events[0].titulo field" && exit 1)
          echo "$response" | jq -e '.events[0].location.lat' > /dev/null || (echo "No events[0].location.lat field" && exit 1)

          echo "JSON response structure is valid"